### PR TITLE
[ADD] stock_lot_invoicing: new module to invoice by lot prices

### PR DESCRIPTION
**Pull request by agaldona**
- TO-DO: Tests

### CODE REVIEW

**Comment by agaldona** [comment]
Tests done! @avanzosc/developers review it please!

**Review by oihane — APPROVED** [review]
LGTM

**Comment by Daniel-CA** [comment]
:+1:

**Comment by Daniel-CA** [comment]
Tienes que hacer rebase

**Comment by alfredoavanzosc** [comment]
:+1:

**Comment by mikelarre** [comment]
:+1:

**Pull request merged**
