### PR TITLE
[IMP] event_track_analytic: employee in account analytic line.

### PR DESCRIPTION
**Pull request by Berezi**

### CODE REVIEW

**Comment by Berezi** [comment]
@anajuaristi @alfredoavanzosc @Daniel-CA @oihane review please.

**Review by alfredoavanzosc — APPROVED** [review]
:+1

**Comment by Berezi** [comment]
@anajuaristi @oihane @Daniel-CA review please.

**Comment by Berezi** [comment]
@anajuaristi @oihane @Daniel-CA review please

**Comment by Berezi** [comment]
@anajuaristi @oihane @Daniel-CA review please.

**Review by anajuaristi — APPROVED** [review]

**Pull request merged**
