### PR TITLE
[FIX] stock_orderpoint_rule: Fixed view to execute correct wizard for…

### PR DESCRIPTION
**Pull request by Daniel-CA**
…m view + Translations update

### CODE REVIEW

**Comment by Daniel-CA** [comment]
@avanzosc/developers review when possible please

**Comment by Daniel-CA** [comment]
Tengo que añadir unas traducciones, no mergear aún.

**Review by alfredoavanzosc — APPROVED** [review]
:+1:

**Review by mikelarre — APPROVED** [review]
:+1:

**Review by agaldona — APPROVED** [review]

**Pull request merged**
